// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdcyygugfdncwyuyakpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkY3l5Z3VnZmRuY3d5dXlha3BpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NzAyNjMsImV4cCI6MjA3MzQ0NjI2M30.6fzDtGf_uiN04Q0Gk-eox9E_t21qzUoM2tPxyU21-PM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});